### ISSUE TITLE
[Feature request] Add the ability to ping mentionable roles via send-to-channel or with an additional action

### ISSUE THREAD

**Issue by blanksuspect** [Twentysix26/x26-Cogs#10]
**Cog**
- [X] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**
I would like to be able to use the `send-to-channel` action to ping a mentionable role. 

For instance, if an `on-emergency` event was triggered, I'd like to be able to send a message to a specific channel like:

`send-to-channel: [HelperAlerts, "@HelperRole, Emergency Mode has been enabled."]` where HelperRole is set to allow mentions.

**Comment by Twentysix26** [comment]
Added in https://github.com/Twentysix26/x26-Cogs/commit/fc3e898fc5db685c8e5955e1ebf0f9b12f1aaac4

The message context variable is escaped automatically to prevent unwanted mentions coming from external sources
