### ISSUE TITLE
[Feature request] Defender should respect cog disabled in guild

### ISSUE THREAD

**Issue by TrustyJAID** [Twentysix26/x26-Cogs#12]
**Cog**
- [x] Defender
- [ ] Index
- [ ] Sbansync

Defenders listeners should respect Red's cog disabled in guild setting. While you have most events locked behind an enabled setting within the cog there's some that don't have an explicit setting and they should still respect cog disabled in guild if a bot owner chooses to set the cog as disabled by default.

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/x26-Cogs/commit/4f79ea511a9195e0c686e2d0c76de2dd1b851d2b
