### ISSUE TITLE
[Feature request] Send embeds to arbitrary channels

### ISSUE THREAD

**Issue by Merp-Me** [Twentysix26/x26-Cogs#16]
**Cog**
- [x] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**
There are two suggestions that would really be nice to include. One of them is supporting embeds for send-in-channel: or any other actions that send message including dm's. It's not a "must have" feature and there is no rush to include it but would just be nice to have that option in the bots embed colour. 

Second feature I was hoping that could be added was the ability to make the issue-command be set so it shows that the bot invoked the command rather than the person who created this rule. One of the reason is that in large servers, you get unwanted dms of people asking me why I kicked/banned them, even though it clearly says on the rule "THIS WAS AN AUTOMATED ACTION" but seems like no one likes reading. 

That's all, even if these don't get implemented, it's alright. I love defender/warden as it is and won't ever stop using it 🥰

**Comment by Twentysix26** [comment]
This is now possible with [`send-message`](https://github.com/Twentysix26/x26-Cogs/wiki/Warden#examples). The other suggestion is not technically feasible.
