### ISSUE TITLE
[textual mistake] in the the conditions part of wardens documents  

### ISSUE THREAD

**Issue by Lime007** [Twentysix26/x26-Cogs#18]
In the first para of conditions for warden on the line there is a word called **patters** assuming u meant patterns .. here's the [link](https://github.com/Twentysix26/x26-Cogs/wiki/Warden#conditions) 
Also attached a ss below ..
![FCC3DCE6-4AF7-4A5C-AD34-4C78481D85B1](https://user-images.githubusercontent.com/75667833/120148704-b99ca380-c1f9-11eb-81dc-7bc0cc9df500.jpeg)

**Comment by Twentysix26** [comment]
Ty
