### ISSUE TITLE
[Feature request] Activity conditions

### ISSUE THREAD

**Issue by XenonUnity** [Twentysix26/x26-Cogs#19]
**Cog**
- [x] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**
I want to start off by saying that this is my 2nd Git issue/request/suggestion thing so I apologise if it's not done correctly.

On my instance of Red I've got two cogs that do this in a somewhat okay but not ideal method. Blocking or alerting staff of rich presence invites/status invites. They do this pretty well but sadly it requires manual execution to do its job. I am currently using Defender to handle message spam, specific keyword filtering, banning users if their username matches x and y and raid detection so it's safe to say I am more than happy with how it works. A little while ago however I was watching over a troll that joined the server and noticed that their custom status was set to an invite link and wondered if Defender could search for statuses that match any form of advertising and either I'm blind and glossed over it or there isn't a way (currently) to do it.

My feature request is to add status or activity scanning for advertising, applying roles if their status matches x/y etc etc. It might make the whole process more resource demanding but that's totally a sacrifice I'm willing to take should this be possible.
If you'd like to contact me for a better explanation, my Discord is ItzXenonUnity | Lou#2369

**Comment by Twentysix26** [comment]
Added in [v1.7](https://github.com/Twentysix26/x26-Cogs/releases/tag/v1.7)
