### ISSUE TITLE
[Feature request] place to post custom scripts for warden

### ISSUE THREAD

**Issue by mon5termatt** [Twentysix26/x26-Cogs#31]
**Cog**
- [x] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**
A clear and concise description of what you'd like to see

Can we get a place to share our custom warden scripts.

Maybe someplace simple like a pinned issue.

**Comment by mon5termatt** [comment]
https://github.com/mon5termatt/Defender-Filters

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/warden-rules

Contributions are welcome
