### ISSUE TITLE
[Enhancement] Name "Requirements" field differently to avoid possible misinterpretation

### ISSUE THREAD

**Issue by jack1142** [Twentysix26/x26-Cogs#4]
**Cog**
- [ ] Defender
- [x] Index
- [ ] Sbansync

**Describe the enhancement**
Similarly to <https://github.com/Cog-Creators/Cog-Browser/issues/10>, it might make sense to call the field differently to avoid users from misinterpreting it as something they need to handle manually.

**Comment by jack1142** [comment]
Welp, I should have used the "Feature request" template to get a more proper label I guess 😬

**Comment by Twentysix26** [comment]
👍🏻  https://github.com/Twentysix26/x26-Cogs/commit/d9b38dfb2c6fb20c6d0ca8c8766907dee20ae6cf
