### ISSUE TITLE
[Feature request] [Defender/Warden] Allow specifying where issue-command runs

### ISSUE THREAD

**Issue by sp00nd** [Twentysix26/x26-Cogs#44]
**Cog**
- [X] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**
Sometimes you just do not want it to run in general chat. 💯

**Comment by Twentysix26** [comment]
Added in [v1.10](https://github.com/Twentysix26/x26-Cogs/releases/tag/v1.10)
