### ISSUE TITLE
[Feature request] [Defender/Warden] Allow replies for sending messages

### ISSUE THREAD

**Issue by sp00nd** [Twentysix26/x26-Cogs#45]
**Cog**
- [X] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**
Allow Warden to **reply** to messages with/without pinging. This would be a better usage instead of having to specify $user_mention in the message send field to direct content to users. You had your own idea for implementation, so I am not going to suggest how you do this, just logging it here as a feature request.

**Comment by Twentysix26** [comment]
Added in [v1.10](https://github.com/Twentysix26/x26-Cogs/releases/tag/v1.10)
