### ISSUE TITLE
[Bug] Unable to execute commands as server owner.

### ISSUE THREAD

**Issue by stefmmm** [Twentysix26/x26-Cogs#5]
**Cog**
- [v1.2.1] Defender
- [N/A] Index
- [N/A] Sbansync

**Describe the bug**
As the bot/server owner i'm unable to invoke commands like 'vaporize' or 'voteout' i get greeted with this message 'You are not authorized to issue this command.' there is only one server of mine where i can successfully invoke these commands, i've checked permissions and reset Defender multiple times with the same result.

**To Reproduce**
1. Issue command 'vaporize'
2. See result

**Expected behavior**
The command should execute the action

**Screenshots**
![Discord_5megQ94niI](https://user-images.githubusercontent.com/35920828/100529507-88aaca00-31e8-11eb-818a-571f05d9dc32.png)
![Discord_fnZ3InAxZx](https://user-images.githubusercontent.com/35920828/100529554-1b4b6900-31e9-11eb-90a9-f664e210f53b.png)

**Comment by Twentysix26** [comment]
The most likely cause is that there are no core Admin / Mod roles set for those servers.
You can verify this with
`[p]set showsettings`
Bot owner / server owner status don't grant any privileges within this cog.

**Comment by stefmmm** [comment]
You're spot on, i totally forgot to set those, it now works as expected, thanks for your time!
