### ISSUE TITLE
[Feature request] message-matches-any, but with regex instead of wildcards

### ISSUE THREAD

**Issue by ProfessorSniff** [Twentysix26/x26-Cogs#6]
**Cog**
- [x] Defender
- [ ] Index
- [ ] Sbansync

**Feature**
Allow use of regex instead of simple wildcards, instead of simple wildcards. (something like https://docs.python.org/3/library/re)
Preferably add a new condition like `message-matches-regex` since regex *is* a lot more complex than wildcards, and would break old rules.

**Comment by Twentysix26** [comment]
Added in https://github.com/Twentysix26/x26-Cogs/compare/7c8eefe56810...ff56ca4ce264
