### ISSUE TITLE
[Bug] Using the reply function in discord the bot doesnt seem to detect the message

### ISSUE THREAD

**Issue by TypicalGhostGuy22** [Twentysix26/x26-Cogs#63]
**Cog**
- [ x] Defender
- [ ] Index
- [ ] Sbansync

**Describe the bug**
Defender - Warden
Ignores new messages sent when a user replies to someone else comment. 

**To Reproduce**
1. Find a post
2. In discord click reply
3. Type something that should be deleted from warden rule
4. When sent the message is not detected and not deleted.

**Expected behavior**
For the Warden to detect the content of the message to delete

**Comment by Twentysix26** [comment]
Ty, fixed in [2.0.1](https://github.com/Twentysix26/x26-Cogs/releases/tag/v2.0.1)
