### ISSUE TITLE
[Feature request] Anti-Raid System

### ISSUE THREAD

**Issue by LillyCosmo** [Twentysix26/x26-Cogs#7]
**Cog**
- [X ] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**

Essentially what this would be doing is looking at the past few messages and see if they are the same thing, so it'd be like antispam but not exclusive to one user, using a shared phrase. For example, if one user said "This is a raid" and the next 8 users said "This is a raid" it'd pick up on this, warn them and delete their messages. However, there'd have to be some time limits as well as role restrictions/whitelisted roles. For example, there are chains, so trusted users/roles we wouldn't want this to be applied to.

**Comment by Twentysix26** [comment]
I don't think the usefulness would quite justify the development effort, especially if we're only talking about exact matches. Detecting *similar* sentences between users could be more useful but that's likely resource intensive, especially on big servers. I'll leave this open to give it some thought but I'm on the verge of no on this one
