### ISSUE TITLE
[Bug] failed to install defender

### ISSUE THREAD

**Issue by jakjakob** [Twentysix26/x26-Cogs#71]
**Cog**
- [ x] Defender
- [ ] Index
- [ ] Sbansync

**Describe the bug**
Received `Failed to install the requirement: pyyaml~=5.4.1` while trying to `[p]cog install x26-cogs defender`

**Comment by Sevenyx** [comment]
Getting the same here.

**Comment by japandotorg** [comment]
I’m not entirely sure but from a small google search, it looks like something’s wrong with pyyaml `5.4.x` as of now - https://github.com/yaml/pyyaml/issues/724

**Comment by jakjakob** [comment]
apparently downgrading to 5.3.1 resolves the issue; or maybe try with 6.0.1?

**Comment by Twentysix26** [comment]
Apologies for the delay, as you can imagine it's a busy time of the year. You can try installing again (maybe re-add the repository first), it should not attempt to install a lower version of pyyaml anymore

**Comment by jakjakob** [comment]
> Apologies for the delay, as you can imagine it's a busy time of the year. You can try installing again (maybe re-add the repository first), it should not attempt to install a lower version of pyyaml anymore

Thx, removing ([p]repo remove x26-cogs) the repository and re-adding it worked for me.
