### ISSUE TITLE
[Feature request] Defender: Event on nickname change

### ISSUE THREAD

**Issue by jakjakob** [Twentysix26/x26-Cogs#79]
**Cog**
- [x ] Defender

**Describe the feature you'd like to see**
Would be nice to have an event called on-nickname-change to better optimise nickname based rules (for example to remove unwanted nicknames etc)

**Comment by EternalllZM** [comment]
Duplicate of https://github.com/Twentysix26/x26-Cogs/issues/59

**Comment by jakjakob** [comment]
closing since duplicate
