### ISSUE TITLE
[Feature Request] Warden Rule Update CMD

### ISSUE THREAD

**Issue by J-Daniel-1** [Twentysix26/x26-Cogs#9]
**Cog**
- [x] Defender
- [ ] Index
- [ ] Sbansync

**Describe the feature you'd like to see**
An update command to warden so we don't have to remove the rule then re-add it, especially if the rule(s) are long. 
`[p]defender warden update <rule>`

**Comment by Twentysix26** [comment]
You don't have to remove and add it again. When you add a rule with the same name it asks you if you want to overwrite it.

**Comment by J-Daniel-1** [comment]
I never knew this

**Comment by Twentysix26** [comment]
I assume that covers this request
