### ISSUE TITLE
[Bug?] No confirmation on [p]defender warden remove

### ISSUE THREAD

**Issue by jakjakob** [Twentysix26/x26-Cogs#93]
**Cog**
- [ x] Defender
- [ ] Index
- [ ] Sbansync

**Describe the bug**

**To Reproduce**
Remove a warden rule via `[p]def wd remove <rule-name>`
There will be no confirmation prompt

**Expected behavior**
Show a confirmation in form of a message or checkmark

**Screenshots**

**Comment by EternalllZM** [comment]
There is a checkmark (✅) reaction when using that command. Does your bot have permissions to add reactions to messages?

If you're referring to confirmation such as needing to check a reaction before the rule deletion goes through, that would be a feature request not a bug. However, I don't agree with adding such a feature personally.

**Comment by jakjakob** [comment]
> There is a checkmark (✅) reaction when using that command. Does your bot have permissions to add reactions to messages?

Yes I refer to that.
Just to be sure I double checked if it worked with other commands, it turns out it didn't (even though before it did). I restarted the bot and then it worked. The problem seems to not be related to the cog, but something bot-wide. 
(I initially didn't double check as it has worked plenty times before)
